<?php

namespace Apw\BlackbullBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{
    public function findChildCategoriesJoinedProducts($id){

        $query =
            $this->getEntityManager()
                ->createQuery('
            SELECT c, cd, p, pd FROM ApwBlackbullBundle:Categories c
            LEFT JOIN c.categoryDescription cd
            LEFT JOIN c.products p
            LEFT JOIN p.productsDescription pd
            WHERE c.parentId = :id'
                )->setParameter('id', $id);
        try{
            return $query->getResult();
        }catch(\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }

    public function listCategoriesToMove($id) {
        $query =
            $this->getEntityManager()
                ->createQuery('
            SELECT c, cd FROM ApwBlackbullBundle:Categories c
            LEFT JOIN c.categoryDescription cd
            WHERE c.id <> :id')->setParameter('id', $id);
        try{
            return $query->getResult();
        }catch(\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }
}