<?php

namespace Apw\BlackbullBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ManufacturersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturersRepository extends EntityRepository
{
}
