<?php

namespace Apw\BlackbullBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    public function findProductInfo($id){
        $qry = $this->getEntityManager()->createQuery(
            'SELECT p, c, pd, cd FROM ApwBlackbullBundle:Products p
            JOIN p.categories c JOIN p.productsDescription pd JOIN c.categoryDescription cd
            WHERE p.id = :id'
        )->setParameter('id',$id);

        try{
            return $qry->getSingleResult();
        } catch(\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }
}
