<?php

namespace Apw\BlackbullBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsImagesRepository extends EntityRepository
{
}
